export enum DamageType {
  SLASHING = 'SLASHING',
  BLUDGEONING = 'BLUDGEONING',
  PIERCING = 'PIERCING',

  FIRE = 'FIRE',
  COLD = 'COLD',
  ACID = 'ACID',
  POISON = 'POISON',
  LIGHTNING = 'LIGHTNING',

  PSYCHIC = 'PSYCHIC',
  FORCE = 'FORCE',
  NECROTIC = 'NECROTIC',
  RADIANT = 'RADIANT',
  THUNDER = 'THUNDER'
}